#!/bin/bash
set -e

echo "Initializing Database: ${MYSQL_DATABASE}"

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS '${MYSQL_DATABASE}';

    CREATE USER IF NOT EXISTS 'crawler'@'%' IDENTIFIED BY '${MYSQL_CRAWLER_PASSWORD}';
    GRANT INSERT, UPDATE, SELECT ON '${MYSQL_DATABASE}'.* TO '${MYSQL_CRAWLER_USER}'@'%';

    CREATE USER IF NOT EXISTS 'web'@'%' IDENTIFIED BY '${MYSQL_WEB_PASSWORD}';
    GRANT SELECT ON '${MYSQL_DATABASE}'.* TO '${MYSQL_WEB_USER}'@'%';
    
    FLUSH PRIVILEGES;
EOSQL

